### ISSUE TITLE
Text written into the chat-box is unreadable

### ISSUE THREAD

**Issue by Vogel612** [rlemon/se-chat-dark-theme-plus#24] opened 2015-11-27 10:32 UTC
A picture is more than a thousand words:

![unreadable](https://cloud.githubusercontent.com/assets/7288995/11439202/46290f88-94fa-11e5-8974-af336652dda5.png)

What's written there is "can" ... Behaviour observed in [this room](https://chat.stackexchange.com/rooms/8595/the-2nd-monitor) in Chrome 46.0.2490.80 under Ubuntu

**Comment by Patsy-issa** [comment] 2015-11-27 11:06
Problem is caused by the site's lovely stylesheet, will push a fix in a bit
<img width="326" alt="screen shot 2015-11-27 at 1 05 54 pm" src="https://cloud.githubusercontent.com/assets/4568519/11439998/aa5bcfec-9507-11e5-9f12-6abd8bdfffac.png">

**Comment by rlemon** [comment] 2016-09-23 19:12
@Patsy-issa did you have a fix for this? I recompiled everything and cleaned up what happened in the last merger -- so I'm taking issues again.

**Comment by rlemon** [comment] 2016-11-08 21:56
this no longer appears to be the case. Please update me if you experience this still.

**Closed by rlemon** 2016-11-08 21:56 UTC
